name: tenjin_demo
description: A new Flutter application to demonstate working of TenjinSDK.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tenjin_sdk: ^0.0.2
  advertising_id: ^0.9.2


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:




  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
